const states = Object.freeze({
  canvas: $("#graph-canvas"),
  rowCountInput: $("#row-count"),
  columnCountInput: $("#column-count"),
  boxSizeInput: $("#box-size"),
  toolModeInput: $("input[name=selectionMode]:radio"),
  clearGraphBtn: $("#clear-graph-btn"),
  resetGraphBtn: $("#reset-graph-btn"),
  startStopBtn: $(".start-stop-btn"),
  width: $("#graph-canvas").width(),
  height: $("#graph-canvas").height(),
  actionPanel: $(".action-panel"),
  algoSelection: $(".algo-selection"),
  algoNameDisplay: $("#selected-algo-name"),
  speedNameDisplay: $("#selected-speed-name"),
  runnerDuration: $("#runner-duration"),
  currentPathSpeed: 6,
  WEIGHTS_VALUE: Object.freeze({
    weight1: 3,
    weight2: 5,
    weight3: 10,
  }),
  DEFAULT_WEIGHT: 3,
  MAX_STATIONS: 6,
  MAX_END_NODE_COUNT: 3,
  MAX_FIXED_FRAME_COUNT: 1200,
  DEFAULT_BOX_SIZE: window.innerWidth > 600 ? 30 : 30,
  COLORS: Object.freeze({
    BOX_BORDER_COLOR: "rgba(150,150,150,0.8)",
    BOX_TYPE_BLOCK_COLORS: ["#2b2b2b", "#1c1c1c"],
    BOX_TYPE_CLEAR_COLOR: "rgb(255,255,255)",
    BOX_TYPE_STATION_COLORS: ["#00c6ff", "#0072ff"],
    BOX_TYPE_START_NODE_COLORS: ["#238c00", "#006b19"],
    BOX_TYPE_END_NODE_COLORS: ["#fa021b", "#bf0013"],
    BOX_TYPE_TRAVERSED_NODE_COLORS: ["#134E5E", "lightgreen"],
    BOX_TYPE_PATH_NODE_COLORS: ["#FF8008", "#FFC837"],
    BOX_TYPE_ERROR_NODE_COLOR: "#6c757d",
    BOX_TYPE_WEIGHT_COLORS: ["#ffa703","#b37400"]
  }),
  DEFAULT_POS: Object.freeze({
    START_X:2,
    START_Y:5,
    END_X:5,
    END_Y:5
  }),
  TOOL_MODE: Object.freeze({
    START_NODE: 0,
    TARGET_NODE: 1,
    WALL_NODES: 2,
    STATION_NODES: 3,
    WEIGHT_NODES: 4
  }),
  BOX_TYPES: Object.freeze({
    BLOCK: 0,
    CLEAR: 1,
    START_NODE: 2,
    END_NODE: 3,
    WEIGHT_NODE: 4,
    STATION_NODE: 5,
    ERROR_NODE: 6,
  }),
  RunnerSpeeds: Object.freeze({
    Fast: 0,
    Medium: 128,
    Slow: 256,
  }),
  Runners: Object.freeze({
    aStar: AStar,
    idAStar: IDAStar,
    bfs: BreadthFirstSearch,
    idDepthFirst: IDDepthFirstSearch,
    bestFirst: AStar,
    dijkstra: AStar,
    travelSales: TravelingSalesman,
    multiStop: MultipleStops,
    biBFS: BiBreadthFirstSearch,
    biAStar: BiAStar,
    biBestFirst: BiAStar,
    biDijkstra: BiAStar
  }),
  Context: {
    ActiveGrid: null,
    Runner:null,
    FREE: true, /*keeps track of whether the runner is free or running*/
    weight:null,
  }
});
